<?php
echo $this->headtitle("User Dashboard");
?>

<div class="row">
						<div class="col-sm-6 col-md-3">
							<div class="db-box box-1">
								<div class="db-box-icon">
									<i class="fa fa-th-large" aria-hidden="true"></i>
								</div>
								<div class="db-box-inner">
									<span>Property Sale</span> <span class="tl-border"><img
										src="assets/images/db/border.png" alt="Image"
										class="img-fluid"></span>
									<h3>7069</h3>
									<span class="rating">43%</span>
								</div>
							</div>
						</div>
						<!-- db-box -->

						<div class="col-sm-6 col-md-3">
							<div class="db-box box-2">
								<div class="db-box-icon">
									<i class="fa fa-eye" aria-hidden="true"></i>
								</div>
								<div class="db-box-inner">
									<span>Property View</span> <span class="tl-border"><img
										src="assets/images/db/border.png" alt="Image"
										class="img-fluid"></span>
									<h3>22,000</h3>
									<span class="rating">25%</span>
								</div>
							</div>
						</div>
						<!-- db-box -->

						<div class="col-sm-6 col-md-3">
							<div class="db-box box-3">
								<div class="db-box-icon">
									<i class="fa fa-bars" aria-hidden="true"></i>
								</div>
								<div class="db-box-inner">
									<span>Property Listed</span> <span class="tl-border"><img
										src="assets/images/db/border.png" alt="Image"
										class="img-fluid"></span>
									<h3>200</h3>
									<span class="rating">30%</span>
								</div>
							</div>
						</div>
						<!-- db-box -->

						<div class="col-sm-6 col-md-3">
							<div class="db-box box-4">
								<div class="db-box-icon">
									<i class="fa fa-globe" aria-hidden="true"></i>
								</div>
								<div class="db-box-inner">
									<span>Total View</span> <span class="tl-border"><img
										src="assets/images/db/border.png" alt="Image"
										class="img-fluid"></span>
									<h3>10,369</h3>
									<span class="rating">90%</span>
								</div>
							</div>
						</div>
						<!-- db-box -->
					</div>

					
