<?php
echo $this->headtitle("Create LIsting");
?>

<h1 class="db-title">Create A Business Listing</h1>

<div class="add-agent bg-white sub-section">

	<div id="create_listing">
		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label>Select A Company</label> <select
						v-if="createdCompany.length" class="form-control"
						v-model="selectedCompany"
						@change="changeSelectedCompany(selectedCompany)">

						<option v-for="option in createdCompany" v-bind:value="option.id">{{
							option.companyTitle}}</option>

					</select>
				</div>
			</div>
			<div class="col-md-1">OR</div>

			<div class="col-md-4">
				<button class="btn btn-block btn-primary" data-toggle="modal"
					data-target="#myModal">Create new Company</button>
			</div>
		</div>


		<!-- <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Agent User Name">
                                </div> -->
		<div v-if="!isSelectedCompany">
			<hr>
			<h2></h2>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label>Listing Name</label> <input type="text"
							class="form-control" placeholder="Listing Name">
					</div>
				</div>
				<div class="col-md-6">
				<label>Business Segment</label>
					<div class="form-group">
						
						<div v-for="option in businessSegment">
							<input type="radio" name="segment" :value="option.id"> <label
								>{{option.segment}}</label><br>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<label>Business Type</label> <select v-if="createdCompany.length"
						class="form-control" v-model="selectedBusinessType">

						<option v-for="option in businessType" v-bind:value="option.id">{{
							option.typename}}</option>

					</select>

				</div>

				<div class="col-md-6">
					<div class="form-group">
						<label>Busines Category</label>

					</div>
				</div>
			</div>

		</div>
		<!-- <div class="form-group">
                                    <div class="add-photo">
                                        <input type="file" name="add-photo" id="add-photo" class="inputfile form-control inputfile-4" data-multiple-caption="{count} files selected" multiple />
                                        <label for="add-photo"><i class="fa fa-camera" aria-hidden="true"></i> <span>Add Photo</span></label>
                                    </div>
                                </div> -->
		<!-- <input type="submit" value="Send Request" class="btn btn-primary"> -->

	</div>
</div>
<!-- add-agent -->




<div id="myModal" class="modal fade" role="dialog">
	<br> <br> <br> <br>
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>

			</div>
			<div class="modal-body">
        <?php echo $this->partial("board_create_company_form")?>
      </div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>

	</div>
</div>

<script>
    let create_listing = new Vue({
        el:"#create_listing",
        data() {
            return {
                createdCompany: [],
                selectedCompany:"",

                isShowNextFieldset:false,

				//Predef
				businessType:[],
				businessSegment:[],

				//Listing Details
				selectedCompanyName:"",
				selectedBusinessType:"",
				
            }
        },

        mounted () {
            this.getCreatedCompany();
			this.getBusinessType();
			this.getBusinessSegment();
        },

        computed:{
            isSelectedCompany(){
                if(this.selectedCompany == ""){
					
                    return true;
                }else{
                    return false;
                }
            },
			selectedCompanName(){
				if(this.selectedCompany != ""){
					return this.setSelectedCompanyName;
					
				}
			}
        },
        methods: {

			setSelectedCompanyName(name){
				this.selectedCompanyName = name;
			 return this.selectedCompanyName;
			},
            changeSelectedCompany(select){
                if(this.selectedCompany != ""){
                  
                }
            },
			getBusinessType(){
				axios.get("/application/get-listing-business-type").then(res=>{
						if(res.status == 200){
							this.businessType = res.data.data;
						}
					}).catch();
			},

			getBusinessSegment(){
				axios.get("/application/get-listing-business-segment").then(res=>{
						if(res.status == 200){
							this.businessSegment = res.data.data;
						}
					}).catch();
			},
            getCreatedCompany() {
                axios.get("/dashboard/board/getcreatedcompany").then(res=>{
						if(res.status == 200){
							this.createdCompany = res.data.data;
						}
					}).catch();
            }
        },
    });
</script>


