<div id="searchbar" class="lt-page-content bg-color">
    <div class="lt-section">
        <div class="section-content section-padding">
            <div class="container">
                <div class="lt-filter-form list-view-tab">
                    <div class="lt-filter-form-content">
                        <div class="lt-filter-form">
                            <form action="<?= $this->url("listings")?>">
                                <div class="form-content">
                                    <div class="search-content">
                                        <input class="form-control" name="search" type="text"
                                               placeholder="Search here..">
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </div>
                                    <div class="form-group">
                                        <select class="form-control">
<!--                                             <option>{{test}}</option> -->
                                            <option>Washington</option>
                                            <option>New Jersey</option>
                                            <option>Los angeles</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <select class="form-control">
                                            <option>State</option>
                                            <option>New York</option>
                                            <option>California</option>
                                            <option>Washington</option>
                                        </select>
                                    </div>
                                    <div class="iocn align-self-center">
                                        <a class="btn" @click="isShowCogs()" ><i class="fa fa-cogs" aria-hidden="true"></i></a>
                                    </div>
                                    <div class="button">
                                        <input type="submit" value="Search" class="btn btn-primary">
                                    </div>
                                </div><!-- /.row -->
                            </form>
                        </div>

                    </div><!-- /.lt-filter-content -->


                </div><!-- /.lt-filter-form -->
            </div><!-- /.container -->
        </div><!-- /.section-content -->

       


    </div><!-- /.lt-section -->
</div><!-- /.lt-page-content -->

<?php echo $this->partial("application/partial/layout_searchbarfilter")?>
<script>
    let searchbar = new Vue({
        el:"#searchbar",
        data(){
            return{
//                 test:"Welcome",
                isShowCog:false,
            }
        },
        methods: {
            isShowCogs(){

                searchFilter.isShowCog =  !searchFilter.isShowCog;
            }
        }
    });
</script>