<header class="tl-header">
    <div class="tl-topbar">
        <div class="container">
            <div class="d-flex justify-content-between">
                <div class="left-content">
                    <ul class="global-list">
                        <li><a href="<?php echo $this->url("home") ?>" ><img src="assets/images/logo.png" alt="Logo" class="img-fluid"></a> <?= $this->defaultFlagRoute() ?> </li>
                    </ul>
                </div><!-- /.left-content -->
                <div class="right-content align-self-center">
                    <div class="topbar-user">
                        <span> <a href="<?= $this->url("login") ?> "><i title="User Account" class="fa fa-user"></i></a> |
                            <span>   </span>
                            <span> <a href="<?= $this->url("login") ?> "><i title="Logout" class="fa fa-sign-out"></i></a></span>

                    </div><!-- /.topbar-user -->

                </div><!-- /.right-content -->
            </div>
        </div><!-- /.container -->
    </div><!-- /.tl-topbar -->




    <?php if (isset($extraTemplate)) {
        echo $this->partial($extraTemplate);
    }
    ?>
</header><!-- /.tl-header -->