<div class="tl-footer">
    <div class="footer-content bg-image" style="background-image: url(assets/images/bg/footer.jpg);">
        <div class="container">
            <div class="footer-top">
                <div class="newsletter justify-content-between">
                    <h3>Subscribe Our Newsletter</h3>
                    <form action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Enter Your E-mail">
                            <input type="submit" class="btn btn-primary" value="Subscribe Now">
                        </div>
                    </form>
                </div>
            </div><!-- /.footer-top -->

            <div class="footer-middle">
                <div class="row">
                    <div class="col-md-8 col-lg-4">
                        <div class="footer-widget">
                            <div class="footer-logo">
                                <img src="assets/images/logo-white.png" alt="Logo" class="img-fluid">
                            </div>
                            <p>Holisticly aggregate compelling ROI before out-of-the-box benefits. Efficiently create cross functional paradigms without an expanded array of testing procedures.</p>
                            <span class="phone-number"><a href="tel:990085627586"> <span class="mr-2 fa fa-phone"></span> 9900 - 8562 - 7586</a></span>
                        </div><!-- /.footer-widget -->
                    </div>
                    <div class="col-md-4 col-lg-2">
                        <div class="footer-widget">
                            <h3>Navigation</h3>
                            <ul class="global-list">
                                <li><a href="about.html">About Us</a></li>
                                <li><a href="property.html">Properties</a></li>
                                <li><a href="team.html">Agents</a></li>
                                <li><a href="property-submit.html">Submit Property</a></li>
                                <li><a href="blog.html">News</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </div><!-- /.footer-widget -->
                    </div>
                    <div class="col-md-8 col-lg-3">
                        <div class="footer-widget">
                            <h3>Recent Post</h3>
                            <div class="tl-post">
                                <div class="entry-header">
                                    <div class="entry-thumbnail">
                                        <a href="blog-details.html"><img src="assets/images/blog/1.png" alt="Image" class="img-fluid"></a>
                                    </div>
                                </div>
                                <div class="entry-content align-self-center">
                                    <h2 class="entry-title"><a href="blog-details.html">Completely aggregate maintainable.</a></h2>
                                    <div class="entry-meta">
                                        <ul class="global-list">
                                            <li>20 May 2019</li>
                                        </ul>
                                    </div>
                                </div>
                            </div><!-- /.tl-post -->

                            <div class="tl-post">
                                <div class="entry-header">
                                    <div class="entry-thumbnail">
                                        <a href="blog-details.html"><img src="assets/images/blog/2.png" alt="Image" class="img-fluid"></a>
                                    </div>
                                </div>
                                <div class="entry-content align-self-center">
                                    <h2 class="entry-title"><a href="blog-details.html">Completely aggregate maintainable.</a></h2>
                                    <div class="entry-meta">
                                        <ul class="global-list">
                                            <li>20 May 2019</li>
                                        </ul>
                                    </div>
                                </div>
                            </div><!-- /.tl-post -->
                        </div><!-- /.footer-widget -->
                    </div>
                    <div class="col-md-4 col-lg-3">
                        <div class="footer-widget">
                            <h3>Property Cities</h3>
                            <ul class="global-list">
                                <li><a href="property.html">New York</a></li>
                                <li><a href="property.html">Sydney</a></li>
                                <li><a href="property.html">Dubai</a></li>
                                <li><a href="property.html">Austin</a></li>
                                <li><a href="property.html">Japan</a></li>
                                <li><a href="property.html">Quatar</a></li>
                            </ul>
                        </div><!-- /.footer-widget -->
                    </div>
                </div><!-- /.row -->
            </div><!-- /.footer-middle -->

            <div class="footer-bottom clearfix">
                <div class="d-flex justify-content-between">
                    <div class="left-content">
                        <span>Erfassen &copy; 2020 Developed by <a href="#">Vecuro</a></span>
                    </div>
                    <div class="right-content">
                        <ul class="global-list d-flex">
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Terms & Condition</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div><!-- /.footer-bottom -->
        </div><!-- /.container -->
    </div><!-- /.footer-content -->
</div><!-- /.tl-footer -->