<div class="lt-banner banner-style-1 bg-image" style="background-image: url(assets/images/bg/banner-bg2.jpg);">
    <div id="home-slider" class="carousel slide home-slider banner-content" data-ride="carousel">
        <div class="carousel-inner text-center">
            <div class="carousel-item active">
                <div class="container">
                    <div class="banner-text">
                        <h1>Find Your</h1>
                        <h2>Dream Home for Living</h2>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal.</p>
                        <form action="#">
                            <div class="form-content">
                                <div class="search-content">
                                    <input class="form-control" name="search" type="text" placeholder="Search here..">
                                    <button type="submit"><i class="fa fa-search"></i></button>
                                </div>
                                <div class="form-group">
                                    <select class="form-control">
                                        <option>City</option>
                                        <option>Washington</option>
                                        <option>New Jersey</option>
                                        <option>Los angeles</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select class="form-control">
                                        <option>State</option>
                                        <option>New York</option>
                                        <option>California</option>
                                        <option>Washington</option>
                                    </select>
                                </div>
                                <div class="button">
                                    <input type="submit" value="Search" class="btn btn-primary">
                                </div>
                            </div><!-- /.row -->
                        </form>
                    </div>
                </div><!-- /.container -->
            </div><!-- /.carousel-item -->

            <div class="carousel-item">
                <div class="container">
                    <div class="banner-text">
                        <h1>Find Your</h1>
                        <h2>Dream Home for Living</h2>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal.</p>
                        <form action="#">
                            <div class="form-content">
                                <div class="search-content">
                                    <input class="form-control" name="search" type="text" placeholder="Search here..">
                                    <button type="submit"><i class="fa fa-search"></i></button>
                                </div>
                                <div class="form-group">
                                    <select class="form-control">
                                        <option>City</option>
                                        <option>Washington</option>
                                        <option>New Jersey</option>
                                        <option>Los angeles</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select class="form-control">
                                        <option>State</option>
                                        <option>New York</option>
                                        <option>California</option>
                                        <option>Washington</option>
                                    </select>
                                </div>
                                <div class="button">
                                    <input type="submit" value="Search" class="btn btn-primary">
                                </div>
                            </div><!-- /.row -->
                        </form>
                    </div>
                </div><!-- /.container -->
            </div><!-- /.carousel-item -->
        </div>
        <a class="carousel-control-prev" href="#home-slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left" aria-hidden="true"></i>
        </a>
        <a class="carousel-control-next" href="#home-slider" role="button" data-slide="next">
            <i class="fa fa-angle-right" aria-hidden="true"></i>
        </a>
    </div><!-- /.home-slider -->
    <div class="mouse-inner-area text-center">
        <div class="container">
            <div class="mouse-inner">
                <div class="thumb">
                    <img src="assets/images/others/mouse-thumb.png" alt="Image" class="img-fluid">
                    <a href="#about" class="mouse-icon">
                        <span class="wheel"></span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                </div>
            </div><!-- /.mouse-inner -->
        </div><!-- /.mouse-inner-area -->
    </div><!-- /.mouse-inner-area -->
</div><!-- /.lt-banner -->
