<header class="tl-header">
    <div class="tl-topbar">
        <div class="container">
            <div class="d-flex justify-content-between">
                <div class="left-content">
                    <ul class="global-list">
                        <li><span class="icon"><img src="assets/images/logo.png" alt="Logo" class="img-fluid"></li>
                    </ul>
                </div><!-- /.left-content -->
                <div class="right-content align-self-center">
                    <div class="topbar-user">
                        <span> <?= $this->defaultFlagRoute() ?></span> | <span> <a href="<?= $this->url("login") ?> ">Login</a> | <a
                                    href="<?= $this->url("user-register")?>>">Sign Up</a></span>
                    </div><!-- /.topbar-user -->
                </div><!-- /.right-content -->
            </div>
        </div><!-- /.container -->
    </div><!-- /.tl-topbar -->




    <?php if (isset($extraTemplate)) {
        echo $this->partial($extraTemplate);
    }
    ?>
</header><!-- /.tl-header -->