<?php
echo $this->headtitle("Subscription Plan");

echo $this->partial("application/partial/layout_dynamic_header");

?>


<div class="lt-section">
    <div class="section-content section-padding bg-color text-center">
        <div class="container">
            <div class="title-center">
                <div class="section-title">
                    <h1>Subscription</h1>
                    <div class="paragraph">
                        <p>Choose from one of Availiable Advertising Plans</p>
                    </div>
                </div>
            </div>

            <div class="feature-content">
                <div class="row">
                    <?php foreach ($packages as $package): ?>
                        <div class="col-md-4">
                            <div class="feature">
                                <div class="feature-icon">
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                </div>
                                <h2><?= $package->getPrice() ?></h2>
                                <p><?= $this->escapehtml($package->getPlanName()) ?></p>
                            </div>
                            <hr>
                            <a href="<?= $this->url("login", array(), array(
                                "query" => array(
                                    "suid" => $package->getPlanUid()
                                )
                            )) ?>" class="btn btn-primary btn-block"> Get Started</a>
                        </div>

                    <?php endforeach; ?>

                </div>
            </div>
        </div><!-- /.container -->
    </div><!-- /.section-content -->
</div><!-- /.lt-section -->