<?php

echo $this->partial("application/partial/layout_dynamic_header");
$this->headtitle("Login");

$form = $this->form;
$form->setAttribute('action', '' /*$this->url('login') */);
$form->setAttribute('class', "lt-form");
$form->prepare();
$fieldset = $form->get("userBasicField");
$fieldset->get('email')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => $this->translate(' Email'),
    'aria-describedby' => 'basic-addon1'
));

$fieldset->get('password')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => $this->translate('Password'),
    'aria-describedby' => 'basic-addon1'
));

$form->get('rememberme')->setAttributes(array(
    'class' => 'remember'
));
$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-primary d-block',
//    "style" => "width: 80%",
    'value' => $this->translate('Log In')
));

?>








<?php // echo $this->partial("general-error-ponters")?>

<div class="lt-page-content bg-color">
    <div class="lt-section">
        <div class="section-content lt-account section-padding">
            <div class="account-content bg-white">
                <h2>Login Into Account</h2>
               <?php echo $this->form()->openTag($form);?>

                    <div class="form-group">

                        <?php echo $this->formElement()->render($fieldset->get('email')); ?>
                        <div class="input-addon">
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                        </div>
                        <div style="font-size: 9px; color: red;">
                            <?php echo $this->formElementErrors($fieldset->get('email')); ?></div>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formElement()->render($fieldset->get('password')); ?>
                        <div class="input-addon">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </div>
                        <div style="font-size: 9px; color: red;">
                            <?php echo $this->formElementErrors($fieldset->get('password')); ?></div>
                    </div>
                    <div class="form-group tnc">
                        <?php
                        echo $this->formRow($form->get('rememberme'));
                        ?>
                        <label for="tnc">Remember Me</label>
                    </div>
                    <?php echo $this->formSubmit($form->get('submit')) ?>
                    <!--                    <a href="dashboard.html" class="">Login</a>-->
                    <div class="social-connect">
                        <a class="facebook" href="#"> <i class="fa fa-facebook" aria-hidden="true"></i> Connect With
                            Facebook</a>
                        <a class="google-plus" href="#"> <i class="fa fa-google-plus" aria-hidden="true"></i> Connect
                            With Google</a>
                    </div>
                    <div class="account-link justify-content-between d-flex">
                        <span>Don’t have an account? <a href="<?php echo $this->url("user-register") ?>" class="color">Sign up</a></span>
                        <span><a href="#">Forgot Password? </a></span>
                    </div>
                <?php $this->form()->closeTag()?>
                <?php

                if ($this->messages) {
                    echo '<div style="font-size: 14px; color: red;">' . $this->messages . '</div>';
                    echo '<div style="font-size: 14px; color: red;">' . $this->error . '</div>';
                };
                ?>
            </div><!-- container -->
        </div><!-- lt-agent-details -->
    </div><!-- lt-section -->
</div><!-- /.lt-page-content -->


<?php
echo $this->formRow($form->get('csrf'));
echo $this->form()->closeTag();
?>






